import React from 'react';
import { motion } from 'framer-motion';
import * as Icons from 'lucide-react';

export const InsightCard = ({ insight, isCompact = false }) => {
  if (!insight) return null;

  const formattedDate = new Date(insight.createdAt).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={`rounded-3xl border transition-all relative overflow-hidden ${
        isCompact
          ? 'p-5 bg-gradient-to-r from-void-card/90 to-void-space/90 border-cosmic-violet/40 hover:border-cyan-electric/40 shadow-xl'
          : 'p-7 glass-panel border-cosmic-violet/40 shadow-2xl'
      }`}
    >
      {/* Background Subtle Star Glow */}
      <div className="absolute top-0 right-0 w-40 h-40 bg-supernova-gold/5 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-40 h-40 bg-cyan-electric/5 rounded-full blur-3xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between mb-3.5">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-supernova-gold/20 border border-supernova-gold/40 flex items-center justify-center text-supernova-gold shadow-glow-gold">
            <Icons.Sparkles className="w-4 h-4" />
          </div>
          <span className="text-xs font-mono font-extrabold uppercase tracking-widest text-supernova-gold">
            Constellation Pattern Insight
          </span>
        </div>
        <span className="text-xs font-mono text-pearl-muted bg-void-space/70 px-3 py-1 rounded-full border border-cosmic-violet/30">
          {formattedDate}
        </span>
      </div>

      {/* Insight Content */}
      <p className={`text-pearl-white leading-relaxed ${isCompact ? 'text-sm' : 'text-base font-normal'}`}>
        "{insight.content}"
      </p>

      {/* Footer / Warm Note */}
      {!isCompact && (
        <div className="mt-5 pt-3.5 border-t border-cosmic-violet/20 flex items-center gap-2 text-xs text-cyan-electric font-mono">
          <Icons.Heart className="w-4 h-4 text-comet-pink" />
          <span>Non-clinical observation generated by Claude AI based on illuminated star patterns</span>
        </div>
      )}
    </motion.div>
  );
};
